permiso_newP:
    path: /newP
    defaults: { _controller: "AppBundle:Permisos:newP"}
    methods: POST

permiso_edit:
    path: /editP/{id}
    defaults: { _controller: "AppBundle:Permisos:newP"}
    methods: POST

permiso_test:
    path: /test
    defaults: { _controller: "AppBundle:Permisos:pruebas"}
    methods: POST

permiso_newR:
    path: /newR
    defaults: { _controller: "AppBundle:Permisos:newR"}
    methods: POST

permiso_editR:
    path: /editR/{id}
    defaults: { _controller: "AppBundle:Permisos:newR"}
    methods: POST

permiso_newPxR:
    path: /newPxR
    defaults: { _controller: "AppBundle:Permisos:newPxR"}
    methods: POST

permiso_editPxR:
    path: /editPxR/{id}
    defaults: { _controller: "AppBundle:Permisos:newPxR"}
    methods: POST

permiso_newRxUxA:
    path: /newRxUxA
    defaults: { _controller: "AppBundle:Permisos:newRxUxA"}
    methods: POST

permiso_roles:
    path: /roles
    defaults: { _controller: "AppBundle:Permisos:roles"}
    methods: POST

permiso_perxrol:
    path: /PxR/{id}
    defaults: { _controller: "AppBundle:Permisos:PerxRol", id:null}
    methods: POST

permiso_rolxuser:
    path: /RxU/{id}
    defaults: { _controller: "AppBundle:Permisos:RolxUser", id:null}
    methods: POST

permiso_userxrol:
    path: /UxR/{id}
    defaults: { _controller: "AppBundle:Permisos:UserxRol", id:null}
    methods: POST

permiso_deleteRol:
    path: /DelRol/{id}
    defaults: { _controller: "AppBundle:Permisos:EliminarRol", id:null}
    methods: POST

permiso_login:
    path: /control
    defaults: { _controller: "AppBundle:Permisos:ControlLogin"}
    methods: POST

permiso_controlPerm:
    path: /contrperm
    defaults: { _controller: "AppBundle:Permisos:ControlPermisos"}
    methods: POST

permiso_aplicaciones:
    path: /apls
    defaults: { _controller: "AppBundle:Permisos:aplicaciones"}
    methods: POST

permiso_newRxA:
    path: /newRxApl
    defaults: { _controller: "AppBundle:Permisos:newRxApl"}
    methods: POST