user_new:
    path: /new
    defaults: { _controller: "AppBundle:User:new"}
    methods: POST

user_edit:
    path: /edit
    defaults: { _controller: "AppBundle:User:edit"}
    methods: POST

user_list:
    path: /list
    defaults: { _controller: "AppBundle:User:users"}
    methods: POST

user_detail:
    path: /user/{id}
    defaults: { _controller: "AppBundle:User:user", id:null}
    methods: POST