BackendBundle\Entity\Aplicacion:
    type: entity
    table: aplicacion
    id:
        idapll:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        descripcionApl:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
            column: descripcion_apl
        fechaCreacion:
            type: datetime
            nullable: true
            column: fecha_creacion
        estado:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
    lifecycleCallbacks: {  }
