BackendBundle\Entity\Permisos:
    type: entity
    table: permisos
    id:
        idPermiso:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_permiso
            generator:
                strategy: IDENTITY
    fields:
        descripPermiso:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: descrip_permiso
        creado:
            type: datetime
            nullable: true
        usuario:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
        estado:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
        nombrePermiso:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
            column: nombre_permiso
    lifecycleCallbacks: {  }
